/**
 * 常用数学符号表（参考 latexlive.com 分类，编译期内联、零网络请求）
 *
 * 分组顺序：先按产品需求指定的十个分组（常用符号 → 数组矩阵），
 * 其后为三个补充分组（二元关系 / 箭头 / 集合与逻辑），
 * 侧边栏「快捷工具」顶部的分组跳转控件即按本数组顺序生成。
 *
 * 说明：`label` 为按钮上直接显示的 Unicode 字符——避免为数百个按钮逐个调用
 * MathJax 渲染，保证面板首开速度；`latex` 为点击后插入源码编辑区的命令。
 * `CURSOR` 表示插入后光标停靠的位置。
 */

import { CURSOR } from '../core/constants';
import type { SymbolGroup, SymbolItem } from '../types';

const s = (label: string, latex: string): SymbolItem => ({ label, latex });
const b = (zh: string, en: string) => ({ zh, en });

export const SYMBOL_GROUPS: SymbolGroup[] = [
	{
		id: 'common',
		name: b('常用符号', 'Common'),
		items: [
			s('±', '\\pm'), s('∓', '\\mp'), s('×', '\\times'), s('÷', '\\div'),
			s('⋅', '\\cdot'), s('∗', '\\ast'), s('∘', '\\circ'), s('∙', '\\bullet'),
			s('≤', '\\leq'), s('≥', '\\geq'), s('≠', '\\neq'), s('≈', '\\approx'),
			s('≡', '\\equiv'), s('∝', '\\propto'), s('∼', '\\sim'), s('≅', '\\cong'),
			s('∞', '\\infty'), s('∂', '\\partial'), s('∇', '\\nabla'), s('∅', '\\emptyset'),
			s('∈', '\\in'), s('∉', '\\notin'), s('⊂', '\\subset'), s('⊆', '\\subseteq'),
			s('∪', '\\cup'), s('∩', '\\cap'), s('∀', '\\forall'), s('∃', '\\exists'),
			s('→', '\\rightarrow'), s('⇒', '\\Rightarrow'), s('↦', '\\mapsto'), s('⇔', '\\Leftrightarrow'),
			s('∴', '\\therefore'), s('∵', '\\because'), s('ℝ', '\\mathbb{R}'), s('□', '\\square'),
		],
	},
	{
		id: 'greek',
		name: b('希腊字母', 'Greek letters'),
		items: [
			s('α', '\\alpha'), s('β', '\\beta'), s('γ', '\\gamma'), s('δ', '\\delta'),
			s('ε', '\\epsilon'), s('ζ', '\\zeta'), s('η', '\\eta'), s('θ', '\\theta'),
			s('ι', '\\iota'), s('κ', '\\kappa'), s('λ', '\\lambda'), s('μ', '\\mu'),
			s('ν', '\\nu'), s('ξ', '\\xi'), s('π', '\\pi'), s('ρ', '\\rho'),
			s('σ', '\\sigma'), s('τ', '\\tau'), s('υ', '\\upsilon'), s('φ', '\\phi'),
			s('χ', '\\chi'), s('ψ', '\\psi'), s('ω', '\\omega'), s('ϵ', '\\varepsilon'),
			s('ϑ', '\\vartheta'), s('ϖ', '\\varpi'), s('ϱ', '\\varrho'), s('ς', '\\varsigma'),
			s('ϕ', '\\varphi'), s('Γ', '\\Gamma'), s('Δ', '\\Delta'), s('Θ', '\\Theta'),
			s('Λ', '\\Lambda'), s('Ξ', '\\Xi'), s('Π', '\\Pi'), s('Σ', '\\Sigma'),
			s('Υ', '\\Upsilon'), s('Φ', '\\Phi'), s('Ψ', '\\Psi'), s('Ω', '\\Omega'),
		],
	},
	{
		id: 'fraction',
		name: b('分数微分', 'Fractions & differentials'),
		items: [
			s('a/b', `\\frac{${CURSOR}}{}`),
			s('a/b 大', `\\dfrac{${CURSOR}}{}`),
			s('a/b 小', `\\tfrac{${CURSOR}}{}`),
			s('连分数', '\\cfrac{1}{1 + \\cfrac{1}{1 + \\cfrac{1}{1}}}'),
			s('a/b 斜', `${CURSOR}/{ }`),
			s('∂', '\\partial'), s('∂²', '\\partial^{2}'), s('∂ᵢ', '\\partial_{i}'),
			s('∂y/∂x', '\\frac{\\partial y}{\\partial x}'),
			s('∂²y/∂x²', '\\frac{\\partial^{2} y}{\\partial x^{2}}'),
			s('∂f/∂x', `\\frac{\\partial ${CURSOR}}{\\partial x}`),
			s('ⅆ', '\\mathrm{d}'), s('ⅆy/ⅆx', '\\frac{\\mathrm{d}y}{\\mathrm{d}x}'),
			s('ⅆf/ⅆx', `\\frac{\\mathrm{d}${CURSOR}}{\\mathrm{d}x}`),
			s('∇', '\\nabla'), s('Δ', '\\Delta'), s('□', '\\square'), s('▪', '\\blacksquare'),
			s('′', "'"), s('″', "''"), s('‴', "'''"), s('∂ₜ', '\\partial_{t}'),
		],
	},
	{
		id: 'radical',
		name: b('根式角标', 'Radicals & scripts'),
		items: [
			s('√', `\\sqrt{${CURSOR}}`), s('ⁿ√', `\\sqrt[n]{${CURSOR}}`),
			s('x²', '^{2}'), s('x³', '^{3}'), s('xⁿ', '^{n}'), s('xₙ', '_{n}'),
			s('xᵢ', '_{i}'), s('x₀', '_{0}'), s('x⁽ⁿ⁾', '^{(n)}'), s('xᵢᵃ', 'x_{i}^{a}'),
			s('ₙCₖ', '_{n}C_{k}'), s('aₙ', 'a_{n}'), s('x̄', `\\overline{${CURSOR}}`),
			s('x̲', `\\underline{${CURSOR}}`), s('x̄ 长', `\\bar{${CURSOR}}`),
			s('x⃗', `\\vec{${CURSOR}}`), s('x̂', `\\hat{${CURSOR}}`),
			s('x̃', `\\tilde{${CURSOR}}`), s('ẋ', `\\dot{${CURSOR}}`),
			s('ẍ', `\\ddot{${CURSOR}}`), s('x⃛', `\\dddot{${CURSOR}}`),
			s('x̂ 宽', `\\widehat{${CURSOR}}`), s('x̃ 宽', `\\widetilde{${CURSOR}}`),
			s('⏞', `\\overbrace{${CURSOR}}`), s('⏟', `\\underbrace{${CURSOR}}`),
			s('ᵃ◌', `\\overset{a}{${CURSOR}}`), s('◌ₐ', `\\underset{a}{${CURSOR}}`),
			s('x→', `\\overset{\\to}{${CURSOR}}`), s('x←', `\\overset{\\leftarrow}{${CURSOR}}`),
		],
	},
	{
		id: 'limits',
		name: b('极限对数', 'Limits & logarithms'),
		items: [
			s('lim', '\\lim'), s('lim→', '\\lim_{x \\to 0}'), s('lim→∞', '\\lim_{n \\to \\infty}'),
			s('lim⁺', '\\lim_{x \\to 0^{+}}'), s('lim⁻', '\\lim_{x \\to 0^{-}}'),
			s('lim‾', '\\limsup'), s('lim_', '\\liminf'),
			s('log', '\\log'), s('ln', '\\ln'), s('lg', '\\lg'),
			s('logₐ', '\\log_{a}'), s('log₁₀', '\\log_{10}'), s('log₂', '\\log_{2}'),
			s('ln x', '\\ln x'), s('log x', '\\log x'), s('eˣ', 'e^{x}'),
			s('exp', '\\exp'), s('aˣ', 'a^{x}'),
			s('max', '\\max'), s('min', '\\min'), s('sup', '\\sup'), s('inf', '\\inf'),
			s('det', '\\det'), s('gcd', '\\gcd'), s('lcm', '\\operatorname{lcm}'),
			s('argmax', '\\argmax'), s('argmin', '\\argmin'), s('deg', '\\deg'),
			s('Pr', '\\Pr'), s('sgn', '\\operatorname{sgn}'),
		],
	},
	{
		id: 'trig',
		name: b('三角函数', 'Trigonometric'),
		items: [
			s('sin', '\\sin'), s('cos', '\\cos'), s('tan', '\\tan'),
			s('cot', '\\cot'), s('sec', '\\sec'), s('csc', '\\csc'),
			s('arcsin', '\\arcsin'), s('arccos', '\\arccos'), s('arctan', '\\arctan'),
			s('arccot', '\\operatorname{arccot}'), s('arcsec', '\\operatorname{arcsec}'),
			s('arccsc', '\\operatorname{arccsc}'),
			s('sin⁻¹', '\\sin^{-1}'), s('cos⁻¹', '\\cos^{-1}'), s('tan⁻¹', '\\tan^{-1}'),
			s('sinh', '\\sinh'), s('cosh', '\\cosh'), s('tanh', '\\tanh'),
			s('coth', '\\coth'), s('sech', '\\operatorname{sech}'), s('csch', '\\operatorname{csch}'),
			s('sin²θ', '\\sin^{2}\\theta'), s('cos²θ', '\\cos^{2}\\theta'),
			s('sin 2θ', '\\sin 2\\theta'), s('cos 2θ', '\\cos 2\\theta'),
			s('tan 2θ', '\\tan 2\\theta'), s('1+tan²', '1 + \\tan^{2}\\theta'),
			s('°', '^{\\circ}'), s('∠', '\\angle'), s('sinh⁻¹', '\\sinh^{-1}'),
		],
	},
	{
		id: 'integral',
		name: b('积分运算', 'Integrals'),
		items: [
			s('∫', '\\int'), s('∬', '\\iint'), s('∭', '\\iiint'), s('∮', '\\oint'),
			s('∫ₐᵇ', '\\int_{a}^{b}'), s('∫₀¹', '\\int_{0}^{1}'), s('∫₋∞∞', '\\int_{-\\infty}^{\\infty}'),
			s('∬_D', '\\iint_{D}'), s('∭_Ω', '\\iiint_{\\Omega}'), s('∮_C', '\\oint_{C}'),
			s('∫fⅆx', '\\int f(x)\\,\\mathrm{d}x'),
			s('∫fⅆx 定', '\\int_{a}^{b} f(x)\\,\\mathrm{d}x'),
			s('∫ᵤ', '\\int_{S}'), s('∫∫∫∫', '\\iiiint'),
			s('∫∫ 域', '\\iint_{D} f(x,y)\\,\\mathrm{d}x\\,\\mathrm{d}y'),
			s('∮F·ⅆl', '\\oint_{C} \\vec{F} \\cdot \\mathrm{d}\\vec{l}'),
			s('∫₀^T', '\\int_{0}^{T}'), s('∫ⅆx/x', '\\int \\frac{\\mathrm{d}x}{x}'),
			s('∂∫', '\\partial \\int'), s('∫ 上下限', '\\int\\limits_{a}^{b}'),
		],
	},
	{
		id: 'bigop',
		name: b('大型运算', 'Large operators'),
		items: [
			s('∑', '\\sum'), s('∏', '\\prod'), s('∐', '\\coprod'),
			s('∑ᵢⁿ', '\\sum_{i=1}^{n}'), s('∑ₙ∞', '\\sum_{n=1}^{\\infty}'),
			s('∑ᵢ', '\\sum_{i}'), s('∏ᵢⁿ', '\\prod_{i=1}^{n}'), s('∏ₙ', '\\prod_{n}'),
			s('⋃', '\\bigcup'), s('⋂', '\\bigcap'), s('⋁', '\\bigvee'), s('⋀', '\\bigwedge'),
			s('⨁', '\\bigoplus'), s('⨂', '\\bigotimes'), s('⨀', '\\bigodot'),
			s('⨄', '\\biguplus'), s('⨆', '\\bigsqcup'), s('⨿', '\\amalg'),
			s('⋃ᵢⁿ', '\\bigcup_{i=1}^{n}'), s('⋂ᵢ', '\\bigcap_{i}'),
			s('∑′', "\\sum'"), s('∫∑', '\\int \\sum'),
			s('⨊', '\\bigsqcup'), s('lim∑', '\\lim_{n \\to \\infty} \\sum'),
			s('∑ᵏ', '\\sum_{k}'), s('∏ⱼ', '\\prod_{j}'),
		],
	},
	{
		id: 'bracket',
		name: b('括号取整', 'Brackets & rounding'),
		items: [
			s('( )', `\\left( ${CURSOR} \\right)`), s('[ ]', `\\left[ ${CURSOR} \\right]`),
			s('{ }', `\\left\\{ ${CURSOR} \\right\\}`), s('⟨ ⟩', `\\left\\langle ${CURSOR} \\right\\rangle`),
			s('| |', `\\left| ${CURSOR} \\right|`), s('‖ ‖', `\\left\\lVert ${CURSOR} \\right\\rVert`),
			s('⌊ ⌋', `\\left\\lfloor ${CURSOR} \\right\\rfloor`),
			s('⌈ ⌉', `\\left\\lceil ${CURSOR} \\right\\rceil`),
			s('⌊ ⌉', `\\left\\lfloor ${CURSOR} \\right\\rceil`),
			s('⟨|', `\\left\\langle ${CURSOR} \\right|`), s('|⟩', `\\left| ${CURSOR} \\right\\rangle`),
			s('( ) 自适应', `\\left( ${CURSOR} \\right)`),
			s('{ } 无定界', `\\{ ${CURSOR} \\}`),
			s('⟦ ⟧', `\\left[\\!\\left[ ${CURSOR} \\right]\\!\\right]`),
			s('( ) 大', '\\Big( \\quad \\Big)'), s('[ ] 大', '\\Big[ \\quad \\Big]'),
			s('⦃ ⦄', `\\left\\{ ${CURSOR} \\right\\}`),
			s('| | 单竖', '\\left| \\quad \\right|'),
			s('nCₖ', `\\binom{n}{${CURSOR}}`), s('nCₖ 大', `\\dbinom{n}{${CURSOR}}`),
			s('nCₖ 小', `\\tbinom{n}{${CURSOR}}`), s('∗', '^{*}'),
			s('⌊x⌋', '\\lfloor x \\rfloor'), s('⌈x⌉', '\\lceil x \\rceil'),
		],
	},
	{
		id: 'matrix',
		name: b('数组矩阵', 'Arrays & matrices'),
		items: [
			s('( )', `\\begin{pmatrix} ${CURSOR} \\end{pmatrix}`),
			s('[ ]', `\\begin{bmatrix} ${CURSOR} \\end{bmatrix}`),
			s('| |', `\\begin{vmatrix} ${CURSOR} \\end{vmatrix}`),
			s('‖ ‖', `\\begin{Vmatrix} ${CURSOR} \\end{Vmatrix}`),
			s('{ }', `\\begin{Bmatrix} ${CURSOR} \\end{Bmatrix}`),
			s('mx', `\\begin{matrix} ${CURSOR} \\end{matrix}`),
			s('小 mx', `\\begin{smallmatrix} ${CURSOR} \\end{smallmatrix}`),
			s('⇉ 分段', `\\begin{cases} ${CURSOR} \\end{cases}`),
			s('⩽ 对齐', `\\begin{align} ${CURSOR} \\end{align}`),
			s('对齐无号', `\\begin{aligned} ${CURSOR} \\end{aligned}`),
			s('arr cc', `\\begin{array}{cc} ${CURSOR} \\end{array}`),
			s('arr cl', `\\begin{array}{cl} ${CURSOR} \\end{array}`),
			s('arr 三线', `\\begin{array}{ccc} ${CURSOR} \\end{array}`),
			s('gather', `\\begin{gathered} ${CURSOR} \\end{gathered}`),
			s('split', `\\begin{split} ${CURSOR} \\end{split}`),
			s('substack', `\\substack{${CURSOR} \\\\ }`),
			s('⋯', '\\cdots'), s('⋮', '\\vdots'), s('⋱', '\\ddots'), s('…', '\\dots'),
			s('&', '&'), s('\\\\', '\\\\'), s('⇉ 2行公式', '\\begin{cases} x, & x > 0 \\\\ 0, & x \\leq 0 \\end{cases}'),
			s('2×2', '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}'),
		],
	},
	{
		id: 'relation',
		name: b('二元关系', 'Relations'),
		items: [
			s('≤', '\\leq'), s('≥', '\\geq'), s('≠', '\\neq'), s('≈', '\\approx'),
			s('≡', '\\equiv'), s('∼', '\\sim'), s('≃', '\\simeq'), s('≅', '\\cong'),
			s('∝', '\\propto'), s('≪', '\\ll'), s('≫', '\\gg'), s('≍', '\\asymp'),
			s('⊂', '\\subset'), s('⊃', '\\supset'), s('⊆', '\\subseteq'), s('⊇', '\\supseteq'),
			s('∈', '\\in'), s('∋', '\\ni'), s('∉', '\\notin'), s('∌', '\\not\\ni'),
			s('⊥', '\\perp'), s('∥', '\\parallel'), s('∤', '\\nmid'), s('∣', '\\mid'),
			s('≺', '\\prec'), s('≻', '\\succ'), s('⪯', '\\preceq'), s('⪰', '\\succeq'),
			s('⊨', '\\models'), s('⊢', '\\vdash'), s('⊣', '\\dashv'), s('⌣', '\\smile'),
			s('≈ 约等', '\\approx'), s('≐', '\\doteq'), s('⋘', '\\lll'), s('≡ 恒等', '\\equiv'),
		],
	},
	{
		id: 'arrow',
		name: b('箭头', 'Arrows'),
		items: [
			s('→', '\\rightarrow'), s('←', '\\leftarrow'), s('↔', '\\leftrightarrow'), s('↦', '\\mapsto'),
			s('⇒', '\\Rightarrow'), s('⇐', '\\Leftarrow'), s('⇔', '\\Leftrightarrow'), s('⟺', '\\iff'),
			s('⟶', '\\longrightarrow'), s('⟵', '\\longleftarrow'), s('⟹', '\\Longrightarrow'), s('⟸', '\\Longleftarrow'),
			s('↑', '\\uparrow'), s('↓', '\\downarrow'), s('↕', '\\updownarrow'), s('⇑', '\\Uparrow'),
			s('⇓', '\\Downarrow'), s('⇕', '\\Updownarrow'), s('↗', '\\nearrow'), s('↘', '\\searrow'),
			s('↖', '\\nwarrow'), s('↙', '\\swarrow'), s('↪', '\\hookrightarrow'), s('↩', '\\hookleftarrow'),
			s('⇀', '\\rightharpoonup'), s('⇁', '\\rightharpoondown'), s('⇝', '\\rightsquigarrow'), s('⇌', '\\rightleftharpoons'),
			s('x→f', '\\overset{f}{\\longrightarrow}'), s('x←g', '\\overset{g}{\\longleftarrow}'),
		],
	},
	{
		id: 'sets',
		name: b('集合与逻辑', 'Sets & logic'),
		items: [
			s('∅', '\\emptyset'), s('∅ 变体', '\\varnothing'), s('ℕ', '\\mathbb{N}'), s('ℤ', '\\mathbb{Z}'),
			s('ℚ', '\\mathbb{Q}'), s('ℝ', '\\mathbb{R}'), s('ℂ', '\\mathbb{C}'), s('ℙ', '\\mathbb{P}'),
			s('∀', '\\forall'), s('∃', '\\exists'), s('∄', '\\nexists'), s('¬', '\\neg'),
			s('∧', '\\land'), s('∨', '\\lor'), s('⊕', '\\oplus'), s('⟹', '\\implies'),
			s('⟺', '\\iff'), s('∴', '\\therefore'), s('∵', '\\because'), s('□', '\\square'),
			s('◇', '\\Diamond'), s('⊤', '\\top'), s('⊥', '\\bot'), s('∖', '\\setminus'),
			s('⨁', '\\oplus'), s('⊘', '\\oslash'), s('⊎', '\\uplus'), s('△', '\\triangle'),
		],
	},
];
